# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/staki/Downloads/clion-2018.1.6/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/staki/Downloads/clion-2018.1.6/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/staki/Desktop/RG107-armagetronrg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/staki/Desktop/RG107-armagetronrg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/staki/Downloads/clion-2018.1.6/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/staki/Downloads/clion-2018.1.6/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/staki/Desktop/RG107-armagetronrg/CMakeFiles /home/staki/Desktop/RG107-armagetronrg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/staki/Desktop/RG107-armagetronrg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Image

# Build rule for target.
Image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Image
.PHONY : Image

# fast build rule for target.
Image/fast:
	$(MAKE) -f CMakeFiles/Image.dir/build.make CMakeFiles/Image.dir/build
.PHONY : Image/fast

#=============================================================================
# Target rules for targets named Soil

# Build rule for target.
Soil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Soil
.PHONY : Soil

# fast build rule for target.
Soil/fast:
	$(MAKE) -f CMakeFiles/Soil.dir/build.make CMakeFiles/Soil.dir/build
.PHONY : Soil/fast

#=============================================================================
# Target rules for targets named Armagetron

# Build rule for target.
Armagetron: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Armagetron
.PHONY : Armagetron

# fast build rule for target.
Armagetron/fast:
	$(MAKE) -f CMakeFiles/Armagetron.dir/build.make CMakeFiles/Armagetron.dir/build
.PHONY : Armagetron/fast

image.o: image.c.o

.PHONY : image.o

# target to build an object file
image.c.o:
	$(MAKE) -f CMakeFiles/Image.dir/build.make CMakeFiles/Image.dir/image.c.o
.PHONY : image.c.o

image.i: image.c.i

.PHONY : image.i

# target to preprocess a source file
image.c.i:
	$(MAKE) -f CMakeFiles/Image.dir/build.make CMakeFiles/Image.dir/image.c.i
.PHONY : image.c.i

image.s: image.c.s

.PHONY : image.s

# target to generate assembly for a file
image.c.s:
	$(MAKE) -f CMakeFiles/Image.dir/build.make CMakeFiles/Image.dir/image.c.s
.PHONY : image.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/Armagetron.dir/build.make CMakeFiles/Armagetron.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/Armagetron.dir/build.make CMakeFiles/Armagetron.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/Armagetron.dir/build.make CMakeFiles/Armagetron.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Image"
	@echo "... edit_cache"
	@echo "... Soil"
	@echo "... Armagetron"
	@echo "... image.o"
	@echo "... image.i"
	@echo "... image.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

